### ISSUE TITLE
Support for TextMate2

### ISSUE THREAD

**Issue by Skoua** [emmetio/emmet-objc#3]
Not really an issue but as TM2 is now open-source and accessible to all, it would be very nice to have a compatible version of Emmet for it.

**Comment by jennie** [comment]
TextMate 2 does not support external plugins. See https://github.com/textmate/textmate/issues/392

**Comment by attilagyorffy** [comment]
:+1:

Would be great if we could do something about this. I wonder, maybe @sorbits would be able to point us to the right direction in order to port the library to TextMate 2.

**Comment by attilagyorffy** [comment]
I've seen the conversation between @sergeche and @sorbits at https://github.com/textmate/textmate/issues/392. Now, I have to admit that I unfortunately have no Objective-C knowledge (otherwise I would have came up with a pull request already) but I'm pretty sure that since TextMate 2 has been made open source, most people have switched to it from the 1.5 branch. Would be great if we could make this amazing plugin to work with TextMate 2, apparently this works for you @sergeche? Cheers.

**Comment by sergeche** [comment]
I’m not ObjC programmer either, but I plan to contribute a few methods to TM2 API to make Emmet work as expected. But TM2 authors may not accept it, the API is not officially available yet.

**Comment by Skoua** [comment]
Isn't possible to make a bundle which would act closely as Emmet?
Wasn't it how it was working on TM1?

**Comment by sergeche** [comment]
No, it’s not possible right now (or at least very hard)

**Comment by igor10k** [comment]
Still no progress?

**Comment by sergeche** [comment]
Not yet

**Comment by sergeche** [comment]
TextMate plugin now works in TextMate 2: https://github.com/emmetio/Emmet.tmplugin

**Comment by kaelig** [comment]
Not anymore apparently?

"The Emmet plug-in is not compatible with this version of TextMate."

I am using TextMate 2 2013-11-03 (v2.0-alpha.9495)

**Comment by sergeche** [comment]
Works fine for me. Make sure you followed the exact installation instruction: https://github.com/emmetio/Emmet.tmplugin#how-to-install

**Comment by kaelig** [comment]
Thanks, works when dragging it to the PlugIns directory :) Sorry about that.
